Repository citation-style-language/documentation, pull requests merged in 2020-06, with the labels that each got.

#68 fix for ambiguous code example for <et-al>
  specification.rst
Labels: 1.0.2, documentation

#82 Revise to emphasize stability and uniqueness of ids
  specification.rst
Labels: documentation

#89 Clarify suppression rules of cs:substitute
  specification.rst
Labels: 1.0.2, clarification, documentation

#95 Add section on whitespace handling
  specification.rst
Labels: 1.0.2, clarification

#86 Add hyperlink recommended rules to the appendix
  specification.rst
Labels: 1.0.2
